[tox]
env_list = py311

[gh-actions]
python =
    3.11: py311

[testenv]
basepython =
    py311: python3.11
usedevelop = true
setenv =
    PYTHONUNBUFFERED = yes
    PYTHONPATH = {toxinidir}/src
passenv = *
deps =
    pytest
    rdkit
    requests
    streamlit
    py3dmol
    ipython
commands =
    pytest tests/